import type { EditorCommand } from "./types";

export const EDIT_COMMANDS: readonly EditorCommand[] = [
  {
    id: "copy",
    label: "Sao chép",
    icon: "copy",
    tab: "edit",
    group: "clipboard",
  },
  { id: "cut", label: "Cắt", icon: "cut", tab: "edit", group: "clipboard" },
  { id: "paste", label: "Dán", icon: "paste", tab: "edit", group: "clipboard" },
  { id: "bold", label: "In đậm", icon: "bold", tab: "edit", group: "font" },
  {
    id: "italic",
    label: "In nghiêng",
    icon: "italic",
    tab: "edit",
    group: "font",
  },
  {
    id: "underline",
    label: "Gạch chân",
    icon: "underline",
    tab: "edit",
    group: "font",
  },
  {
    id: "subscript",
    label: "Chỉ số dưới",
    icon: "subscript",
    tab: "edit",
    group: "font",
  },
  {
    id: "superscript",
    label: "Chỉ số trên",
    icon: "superscript",
    tab: "edit",
    group: "font",
  },
  {
    id: "highlight",
    label: "Tô nền",
    icon: "highlight",
    tab: "edit",
    group: "font",
  },
  {
    id: "text-color",
    label: "Màu chữ",
    icon: "text-color",
    tab: "edit",
    group: "font",
  },
  {
    id: "ordered-list",
    label: "Danh sách số",
    icon: "list-ordered",
    tab: "edit",
    group: "list",
  },
  {
    id: "bullet-list",
    label: "Danh sách dấu đầu dòng",
    icon: "list-bullet",
    tab: "edit",
    group: "list",
  },
  {
    id: "align-left",
    label: "Căn trái",
    icon: "align-left",
    tab: "edit",
    group: "alignment",
  },
  {
    id: "align-center",
    label: "Căn giữa",
    icon: "align-center",
    tab: "edit",
    group: "alignment",
  },
  {
    id: "align-right",
    label: "Căn phải",
    icon: "align-right",
    tab: "edit",
    group: "alignment",
  },
  {
    id: "align-justify",
    label: "Căn đều",
    icon: "align-justify",
    tab: "edit",
    group: "alignment",
  },
  {
    id: "insert-math",
    label: "Công thức",
    icon: "sigma",
    tab: "edit",
    group: "insert",
  },
  {
    id: "insert-image",
    label: "Chèn ảnh",
    icon: "image",
    tab: "edit",
    group: "insert",
  },
  {
    id: "insert-table",
    label: "Chèn bảng",
    icon: "table",
    tab: "edit",
    group: "insert",
  },
  {
    id: "insert-code",
    label: "Khối mã",
    icon: "code",
    tab: "edit",
    group: "insert",
  },
] as const;

export const TABLE_COMMANDS: readonly EditorCommand[] = [
  {
    id: "insert-row-above",
    label: "Thêm hàng phía trên",
    icon: "insert-row-above",
    tab: "table",
    group: "rows",
  },
  {
    id: "insert-row-below",
    label: "Thêm hàng phía dưới",
    icon: "insert-row-below",
    tab: "table",
    group: "rows",
  },
  {
    id: "insert-col-left",
    label: "Thêm cột bên trái",
    icon: "insert-col-left",
    tab: "table",
    group: "columns",
  },
  {
    id: "delete-rows",
    label: "Xóa hàng",
    icon: "delete-rows",
    tab: "table",
    group: "rows",
  },
  {
    id: "insert-col-right",
    label: "Thêm cột bên phải",
    icon: "insert-col-right",
    tab: "table",
    group: "columns",
  },
  {
    id: "delete-columns",
    label: "Xóa cột",
    icon: "delete-columns",
    tab: "table",
    group: "columns",
  },
  {
    id: "merge-cells",
    label: "Gộp ô",
    icon: "merge",
    tab: "table",
    group: "cells",
  },
  {
    id: "split-cells",
    label: "Tách ô",
    icon: "split",
    tab: "table",
    group: "cells",
  },
] as const;

export const PICTURE_COMMANDS: readonly EditorCommand[] = [
  {
    id: "image-center",
    label: "Giữa dòng",
    icon: "image-centered",
    tab: "picture",
    group: "layout",
  },
  {
    id: "image-float-right",
    label: "Trôi phải",
    icon: "float-right",
    tab: "picture",
    group: "layout",
  },
  {
    id: "image-grow",
    label: "Phóng to",
    icon: "zoom-in",
    tab: "picture",
    group: "size",
  },
  {
    id: "image-shrink",
    label: "Thu nhỏ",
    icon: "zoom-out",
    tab: "picture",
    group: "size",
  },
  {
    id: "image-crop",
    label: "Cắt ảnh",
    icon: "crop",
    tab: "picture",
    group: "edit",
  },
  {
    id: "image-rotate-left",
    label: "Xoay trái",
    icon: "rotate-ccw",
    tab: "picture",
    group: "edit",
  },
  {
    id: "image-rotate-right",
    label: "Xoay phải",
    icon: "rotate-cw",
    tab: "picture",
    group: "edit",
  },
  {
    id: "image-replace",
    label: "Thay ảnh",
    icon: "upload",
    tab: "picture",
    group: "manage",
  },
  {
    id: "image-delete",
    label: "Xóa ảnh",
    icon: "trash",
    tab: "picture",
    group: "manage",
  },
] as const;

export const COMMANDS_BY_TAB = {
  edit: EDIT_COMMANDS,
  table: TABLE_COMMANDS,
  picture: PICTURE_COMMANDS,
} as const;
