--
-- PostgreSQL database dump
--

\restrict 5hxn45kwvZHgTWZLuDm4bpXM71T5YRqFNIyEOgeUTZO7WKovSIM1RzKQVw8hZcm

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    public_id uuid DEFAULT gen_random_uuid(),
    email character varying NOT NULL,
    password character varying NOT NULL,
    is_active boolean DEFAULT true,
    role character varying NOT NULL,
    create_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name character varying,
    avatar_url character varying,
    CONSTRAINT check_valid_role CHECK (((role)::text = ANY (ARRAY[('student'::character varying)::text, ('teacher'::character varying)::text, ('admin'::character varying)::text])))
);


--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.accounts_id_seq OWNED BY public.accounts.id;


--
-- Name: class_coding_assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_coding_assignments (
    class_id bigint NOT NULL,
    assignment_id bigint NOT NULL,
    assigned_by bigint,
    assigned_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: class_contests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_contests (
    class_id bigint NOT NULL,
    contest_id bigint NOT NULL,
    assigned_by bigint,
    assigned_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classes (
    id bigint NOT NULL,
    teacher_id bigint,
    public_id uuid DEFAULT gen_random_uuid(),
    class_name text NOT NULL,
    description text,
    create_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    student_count integer DEFAULT 0,
    contest_count integer DEFAULT 0
);


--
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: classes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.classes_id_seq OWNED BY public.classes.id;


--
-- Name: coding_assignment_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coding_assignment_questions (
    assignment_id bigint NOT NULL,
    question_id bigint NOT NULL,
    order_index integer DEFAULT 0 NOT NULL,
    point_weight numeric(8,2) DEFAULT 1 NOT NULL,
    max_submissions_override integer,
    CONSTRAINT coding_assignment_questions_max_submissions_override_check CHECK (((max_submissions_override IS NULL) OR (max_submissions_override > 0))),
    CONSTRAINT coding_assignment_questions_point_weight_check CHECK ((point_weight >= (0)::numeric))
);


--
-- Name: coding_assignment_students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coding_assignment_students (
    id bigint NOT NULL,
    assignment_id bigint NOT NULL,
    student_id bigint NOT NULL,
    started_at timestamp without time zone,
    last_activity_at timestamp without time zone,
    completed_at timestamp without time zone,
    status character varying(20) DEFAULT 'not_started'::character varying NOT NULL,
    total_score numeric(10,2) DEFAULT 0 NOT NULL,
    CONSTRAINT coding_assignment_students_status_check CHECK (((status)::text = ANY ((ARRAY['not_started'::character varying, 'in_progress'::character varying, 'completed'::character varying])::text[])))
);


--
-- Name: coding_assignment_students_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coding_assignment_students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coding_assignment_students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coding_assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coding_assignments (
    id bigint NOT NULL,
    class_id bigint,
    teacher_id bigint NOT NULL,
    public_id uuid DEFAULT gen_random_uuid() NOT NULL,
    legacy_contest_id bigint,
    title text NOT NULL,
    description text,
    available_from timestamp without time zone,
    due_at timestamp without time zone,
    status character varying(20) DEFAULT 'draft'::character varying NOT NULL,
    allow_late_submission boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    allow_link_access boolean DEFAULT false NOT NULL,
    time_limit integer,
    question_count integer DEFAULT 0 NOT NULL,
    student_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT coding_assignments_check CHECK (((due_at IS NULL) OR (available_from IS NULL) OR (due_at >= available_from))),
    CONSTRAINT coding_assignments_status_check CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'published'::character varying, 'closed'::character varying])::text[]))),
    CONSTRAINT coding_assignments_time_limit_check CHECK (((time_limit IS NULL) OR (time_limit > 0)))
);


--
-- Name: coding_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coding_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coding_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coding_submission_testcase_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coding_submission_testcase_results (
    id bigint NOT NULL,
    submission_id bigint NOT NULL,
    testcase_id bigint,
    order_index integer NOT NULL,
    input_data text,
    expected_output text,
    actual_output text,
    status character varying(50) DEFAULT 'Pending'::character varying NOT NULL,
    runtime_ms integer,
    memory_kb integer,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: coding_submission_testcase_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coding_submission_testcase_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coding_submission_testcase_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contest_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contest_results (
    id bigint NOT NULL,
    student_id bigint,
    contest_id bigint,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    total_score numeric,
    count_wrong_answers integer,
    display_order text,
    guest_name character varying
);


--
-- Name: contest_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.contest_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: contest_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.contest_results_id_seq OWNED BY public.contest_results.id;


--
-- Name: contests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contests (
    id bigint NOT NULL,
    class_id bigint,
    public_id uuid DEFAULT gen_random_uuid(),
    title text NOT NULL,
    time_limit integer NOT NULL,
    scoring_config jsonb,
    status character varying NOT NULL,
    teacher_id bigint,
    allow_guest_link boolean DEFAULT false NOT NULL,
    available_from timestamp without time zone,
    due_at timestamp without time zone,
    allow_late_submission boolean DEFAULT false NOT NULL,
    question_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT contests_submission_window_check CHECK (((due_at IS NULL) OR (available_from IS NULL) OR (due_at >= available_from)))
);


--
-- Name: contests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.contests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: contests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.contests_id_seq OWNED BY public.contests.id;


--
-- Name: contests_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contests_questions (
    contest_id bigint NOT NULL,
    question_id bigint NOT NULL,
    original_order integer,
    point_weight numeric
);


--
-- Name: q_choice_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.q_choice_details (
    id bigint NOT NULL,
    question_id bigint,
    content jsonb,
    is_correct boolean DEFAULT false NOT NULL,
    order_index integer NOT NULL,
    is_shufflable boolean DEFAULT true NOT NULL,
    CONSTRAINT q_choice_content_is_doc CHECK (((content IS NULL) OR ((content ->> 'type'::text) = 'doc'::text)))
);


--
-- Name: q_choice_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.q_choice_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: q_choice_details_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.q_choice_details_id_seq OWNED BY public.q_choice_details.id;


--
-- Name: q_coding_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.q_coding_details (
    question_id bigint NOT NULL,
    time_limit_c_cpp double precision DEFAULT 1.0,
    time_limit_java double precision DEFAULT 2.0,
    time_limit_python double precision DEFAULT 2.0,
    memory_limit integer DEFAULT 256,
    max_submissions integer DEFAULT 10,
    solution_code text,
    solution_language character varying(50)
);


--
-- Name: q_coding_testcases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.q_coding_testcases (
    id bigint NOT NULL,
    question_id bigint,
    input_data text NOT NULL,
    output_data text NOT NULL,
    point_weight integer DEFAULT 1,
    is_public boolean DEFAULT false,
    description text,
    order_index integer DEFAULT 0,
    is_sample boolean DEFAULT false
);


--
-- Name: q_coding_testcases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.q_coding_testcases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: q_coding_testcases_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.q_coding_testcases_id_seq OWNED BY public.q_coding_testcases.id;


--
-- Name: q_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.q_images (
    id bigint NOT NULL,
    question_id bigint,
    storage_path text,
    img_type character varying,
    width numeric(4,3),
    raw_code text,
    CONSTRAINT q_images_type CHECK (((img_type)::text = ANY ((ARRAY['tikz'::character varying, 'graphic'::character varying])::text[]))),
    CONSTRAINT q_images_width_range CHECK (((width IS NULL) OR ((width > (0)::numeric) AND (width <= (3)::numeric))))
);


--
-- Name: q_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.q_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: q_images_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.q_images_id_seq OWNED BY public.q_images.id;


--
-- Name: q_shortans_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.q_shortans_details (
    id bigint NOT NULL,
    question_id bigint,
    content text
);


--
-- Name: q_shortans_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.q_shortans_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: q_shortans_details_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.q_shortans_details_id_seq OWNED BY public.q_shortans_details.id;


--
-- Name: q_truefalse_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.q_truefalse_details (
    id bigint NOT NULL,
    question_id bigint,
    content jsonb,
    is_correct boolean DEFAULT false NOT NULL,
    explaination jsonb,
    order_index integer NOT NULL,
    is_shufflable boolean DEFAULT true NOT NULL,
    CONSTRAINT q_tf_content_is_doc CHECK (((content IS NULL) OR ((content ->> 'type'::text) = 'doc'::text))),
    CONSTRAINT q_tf_explaination_is_doc CHECK (((explaination IS NULL) OR ((explaination ->> 'type'::text) = 'doc'::text)))
);


--
-- Name: q_truefalse_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.q_truefalse_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: q_truefalse_details_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.q_truefalse_details_id_seq OWNED BY public.q_truefalse_details.id;


--
-- Name: questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.questions (
    id bigint NOT NULL,
    teacher_id bigint,
    public_id uuid DEFAULT gen_random_uuid(),
    subject text,
    grade integer,
    parent_id bigint,
    question_type character varying,
    layout_type character varying,
    content jsonb,
    solution jsonb,
    chapter text,
    lesson text,
    complexity smallint,
    is_shufflable boolean,
    deleted_at timestamp without time zone,
    CONSTRAINT questions_content_is_doc CHECK (((content IS NULL) OR ((content ->> 'type'::text) = 'doc'::text))),
    CONSTRAINT questions_side_matches_layout CHECK (((content IS NULL) OR (((COALESCE(layout_type, 'normal'::character varying))::text = 'normal'::text) AND (COALESCE((content ->> 'side'::text), 'center'::text) = 'center'::text)) OR (((layout_type)::text ~~ 'immini%'::text) AND ((content ->> 'side'::text) = ANY (ARRAY['left'::text, 'right'::text]))))),
    CONSTRAINT questions_solution_is_doc CHECK (((solution IS NULL) OR ((solution ->> 'type'::text) = 'doc'::text)))
);


--
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: questions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.questions_id_seq OWNED BY public.questions.id;


--
-- Name: student_coding_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_coding_submissions (
    id bigint NOT NULL,
    contest_result_id bigint,
    question_id bigint,
    source_code text NOT NULL,
    language character varying(50) NOT NULL,
    status character varying(50) DEFAULT 'Pending'::character varying,
    runtime_ms integer,
    memory_kb integer,
    score double precision DEFAULT 0.0,
    submitted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    assignment_student_id bigint,
    attempt_number integer,
    compiler_output text
);


--
-- Name: student_coding_submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.student_coding_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: student_coding_submissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.student_coding_submissions_id_seq OWNED BY public.student_coding_submissions.id;


--
-- Name: student_option_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_option_submissions (
    id bigint NOT NULL,
    contest_result_id bigint,
    question_id bigint,
    student_choice text,
    option_display_order text,
    is_correct boolean DEFAULT false,
    earned_point numeric(5,4) DEFAULT 0
);


--
-- Name: student_option_submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.student_option_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: student_option_submissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.student_option_submissions_id_seq OWNED BY public.student_option_submissions.id;


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    school character varying
);


--
-- Name: students_classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students_classes (
    student_id bigint NOT NULL,
    class_id bigint NOT NULL,
    create_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: students_contests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students_contests (
    student_id bigint NOT NULL,
    contest_id bigint NOT NULL
);


--
-- Name: teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teachers (
    id bigint NOT NULL,
    organization character varying,
    question_count integer DEFAULT 0
);


--
-- Name: accounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts ALTER COLUMN id SET DEFAULT nextval('public.accounts_id_seq'::regclass);


--
-- Name: classes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes ALTER COLUMN id SET DEFAULT nextval('public.classes_id_seq'::regclass);


--
-- Name: contest_results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_results ALTER COLUMN id SET DEFAULT nextval('public.contest_results_id_seq'::regclass);


--
-- Name: contests id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contests ALTER COLUMN id SET DEFAULT nextval('public.contests_id_seq'::regclass);


--
-- Name: q_choice_details id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_choice_details ALTER COLUMN id SET DEFAULT nextval('public.q_choice_details_id_seq'::regclass);


--
-- Name: q_coding_testcases id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_coding_testcases ALTER COLUMN id SET DEFAULT nextval('public.q_coding_testcases_id_seq'::regclass);


--
-- Name: q_images id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_images ALTER COLUMN id SET DEFAULT nextval('public.q_images_id_seq'::regclass);


--
-- Name: q_shortans_details id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_shortans_details ALTER COLUMN id SET DEFAULT nextval('public.q_shortans_details_id_seq'::regclass);


--
-- Name: q_truefalse_details id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_truefalse_details ALTER COLUMN id SET DEFAULT nextval('public.q_truefalse_details_id_seq'::regclass);


--
-- Name: questions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions ALTER COLUMN id SET DEFAULT nextval('public.questions_id_seq'::regclass);


--
-- Name: student_coding_submissions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_coding_submissions ALTER COLUMN id SET DEFAULT nextval('public.student_coding_submissions_id_seq'::regclass);


--
-- Name: student_option_submissions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_option_submissions ALTER COLUMN id SET DEFAULT nextval('public.student_option_submissions_id_seq'::regclass);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_public_id_key UNIQUE (public_id);


--
-- Name: contests check_valid_status; Type: CHECK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.contests
    ADD CONSTRAINT check_valid_status CHECK (((status)::text = ANY (ARRAY[('active'::character varying)::text, ('inactive'::character varying)::text, ('deleted'::character varying)::text]))) NOT VALID;


--
-- Name: class_coding_assignments class_coding_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_coding_assignments
    ADD CONSTRAINT class_coding_assignments_pkey PRIMARY KEY (class_id, assignment_id);


--
-- Name: class_contests class_contests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_contests
    ADD CONSTRAINT class_contests_pkey PRIMARY KEY (class_id, contest_id);


--
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- Name: classes classes_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_public_id_key UNIQUE (public_id);


--
-- Name: coding_assignment_questions coding_assignment_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignment_questions
    ADD CONSTRAINT coding_assignment_questions_pkey PRIMARY KEY (assignment_id, question_id);


--
-- Name: coding_assignment_students coding_assignment_students_assignment_id_student_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignment_students
    ADD CONSTRAINT coding_assignment_students_assignment_id_student_id_key UNIQUE (assignment_id, student_id);


--
-- Name: coding_assignment_students coding_assignment_students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignment_students
    ADD CONSTRAINT coding_assignment_students_pkey PRIMARY KEY (id);


--
-- Name: coding_assignments coding_assignments_legacy_contest_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignments
    ADD CONSTRAINT coding_assignments_legacy_contest_id_key UNIQUE (legacy_contest_id);


--
-- Name: coding_assignments coding_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignments
    ADD CONSTRAINT coding_assignments_pkey PRIMARY KEY (id);


--
-- Name: coding_assignments coding_assignments_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignments
    ADD CONSTRAINT coding_assignments_public_id_key UNIQUE (public_id);


--
-- Name: coding_submission_testcase_results coding_submission_testcase_result_submission_id_order_index_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_submission_testcase_results
    ADD CONSTRAINT coding_submission_testcase_result_submission_id_order_index_key UNIQUE (submission_id, order_index);


--
-- Name: coding_submission_testcase_results coding_submission_testcase_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_submission_testcase_results
    ADD CONSTRAINT coding_submission_testcase_results_pkey PRIMARY KEY (id);


--
-- Name: contest_results contest_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_results
    ADD CONSTRAINT contest_results_pkey PRIMARY KEY (id);


--
-- Name: contests contests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contests
    ADD CONSTRAINT contests_pkey PRIMARY KEY (id);


--
-- Name: contests contests_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contests
    ADD CONSTRAINT contests_public_id_key UNIQUE (public_id);


--
-- Name: contests_questions pk_contests_questions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contests_questions
    ADD CONSTRAINT pk_contests_questions PRIMARY KEY (contest_id, question_id);


--
-- Name: q_choice_details q_choice_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_choice_details
    ADD CONSTRAINT q_choice_details_pkey PRIMARY KEY (id);


--
-- Name: q_coding_details q_coding_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_coding_details
    ADD CONSTRAINT q_coding_details_pkey PRIMARY KEY (question_id);


--
-- Name: q_coding_testcases q_coding_testcases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_coding_testcases
    ADD CONSTRAINT q_coding_testcases_pkey PRIMARY KEY (id);


--
-- Name: q_images q_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_images
    ADD CONSTRAINT q_images_pkey PRIMARY KEY (id);


--
-- Name: q_shortans_details q_shortans_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_shortans_details
    ADD CONSTRAINT q_shortans_details_pkey PRIMARY KEY (id);


--
-- Name: q_truefalse_details q_truefalse_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_truefalse_details
    ADD CONSTRAINT q_truefalse_details_pkey PRIMARY KEY (id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- Name: questions questions_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_public_id_key UNIQUE (public_id);


--
-- Name: student_coding_submissions student_coding_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_coding_submissions
    ADD CONSTRAINT student_coding_submissions_pkey PRIMARY KEY (id);


--
-- Name: student_option_submissions student_option_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_option_submissions
    ADD CONSTRAINT student_option_submissions_pkey PRIMARY KEY (id);


--
-- Name: students_classes students_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students_classes
    ADD CONSTRAINT students_classes_pkey PRIMARY KEY (student_id, class_id);


--
-- Name: students_contests students_contests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students_contests
    ADD CONSTRAINT students_contests_pkey PRIMARY KEY (student_id, contest_id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: idx_accounts_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_accounts_email ON public.accounts USING btree (email);


--
-- Name: idx_class_coding_assignments_assignment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_class_coding_assignments_assignment ON public.class_coding_assignments USING btree (assignment_id);


--
-- Name: idx_class_contests_contest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_class_contests_contest ON public.class_contests USING btree (contest_id);


--
-- Name: idx_classes_public_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_classes_public_id ON public.classes USING btree (public_id);


--
-- Name: idx_classes_teacher_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_classes_teacher_id ON public.classes USING btree (teacher_id);


--
-- Name: idx_coding_assignment_students_student; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_coding_assignment_students_student ON public.coding_assignment_students USING btree (student_id);


--
-- Name: idx_coding_assignments_class; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_coding_assignments_class ON public.coding_assignments USING btree (class_id);


--
-- Name: idx_coding_assignments_teacher; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_coding_assignments_teacher ON public.coding_assignments USING btree (teacher_id);


--
-- Name: idx_coding_submissions_progress_question; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_coding_submissions_progress_question ON public.student_coding_submissions USING btree (assignment_student_id, question_id, submitted_at DESC);


--
-- Name: idx_coding_testcase_results_submission; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_coding_testcase_results_submission ON public.coding_submission_testcase_results USING btree (submission_id, order_index);


--
-- Name: idx_contest_results_contest_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contest_results_contest_id ON public.contest_results USING btree (contest_id);


--
-- Name: idx_contests_class_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contests_class_id ON public.contests USING btree (class_id);


--
-- Name: idx_contests_questions_contest_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contests_questions_contest_id ON public.contests_questions USING btree (contest_id);


--
-- Name: idx_contests_teacher_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contests_teacher_id ON public.contests USING btree (teacher_id);


--
-- Name: idx_q_choice_details_question_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_q_choice_details_question_id ON public.q_choice_details USING btree (question_id);


--
-- Name: idx_q_images_question_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_q_images_question_id ON public.q_images USING btree (question_id);


--
-- Name: idx_questions_content_text; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_questions_content_text ON public.questions USING gin (to_tsvector('simple'::regconfig, (content)::text));


--
-- Name: idx_questions_dashboard; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_questions_dashboard ON public.questions USING btree (teacher_id) WHERE ((deleted_at IS NULL) AND (parent_id IS NULL));


--
-- Name: idx_questions_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_questions_parent_id ON public.questions USING btree (parent_id) WHERE (parent_id IS NOT NULL);


--
-- Name: idx_questions_search; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_questions_search ON public.questions USING btree (teacher_id, subject, grade) WHERE (deleted_at IS NULL);


--
-- Name: idx_sc_class_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sc_class_id ON public.students_classes USING btree (class_id);


--
-- Name: idx_sc_student_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sc_student_id ON public.students_classes USING btree (student_id);


--
-- Name: idx_students_classes_class_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_students_classes_class_id ON public.students_classes USING btree (class_id);


--
-- Name: uq_coding_submission_attempt; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_coding_submission_attempt ON public.student_coding_submissions USING btree (assignment_student_id, question_id, attempt_number) WHERE ((assignment_student_id IS NOT NULL) AND (attempt_number IS NOT NULL));


--
-- Name: uq_submission_result_question; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_submission_result_question ON public.student_option_submissions USING btree (contest_result_id, question_id);


--
-- Name: class_coding_assignments class_coding_assignments_assigned_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_coding_assignments
    ADD CONSTRAINT class_coding_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.accounts(id) ON DELETE SET NULL;


--
-- Name: class_coding_assignments class_coding_assignments_assignment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_coding_assignments
    ADD CONSTRAINT class_coding_assignments_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.coding_assignments(id) ON DELETE CASCADE;


--
-- Name: class_coding_assignments class_coding_assignments_class_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_coding_assignments
    ADD CONSTRAINT class_coding_assignments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;


--
-- Name: class_contests class_contests_assigned_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_contests
    ADD CONSTRAINT class_contests_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.accounts(id) ON DELETE SET NULL;


--
-- Name: class_contests class_contests_class_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_contests
    ADD CONSTRAINT class_contests_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE;


--
-- Name: class_contests class_contests_contest_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_contests
    ADD CONSTRAINT class_contests_contest_id_fkey FOREIGN KEY (contest_id) REFERENCES public.contests(id) ON DELETE CASCADE;


--
-- Name: coding_assignment_questions coding_assignment_questions_assignment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignment_questions
    ADD CONSTRAINT coding_assignment_questions_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.coding_assignments(id) ON DELETE CASCADE;


--
-- Name: coding_assignment_questions coding_assignment_questions_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignment_questions
    ADD CONSTRAINT coding_assignment_questions_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE RESTRICT;


--
-- Name: coding_assignment_students coding_assignment_students_assignment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignment_students
    ADD CONSTRAINT coding_assignment_students_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.coding_assignments(id) ON DELETE CASCADE;


--
-- Name: coding_assignment_students coding_assignment_students_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignment_students
    ADD CONSTRAINT coding_assignment_students_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: coding_assignments coding_assignments_class_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignments
    ADD CONSTRAINT coding_assignments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE SET NULL;


--
-- Name: coding_assignments coding_assignments_legacy_contest_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignments
    ADD CONSTRAINT coding_assignments_legacy_contest_id_fkey FOREIGN KEY (legacy_contest_id) REFERENCES public.contests(id) ON DELETE SET NULL;


--
-- Name: coding_assignments coding_assignments_teacher_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_assignments
    ADD CONSTRAINT coding_assignments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: coding_submission_testcase_results coding_submission_testcase_results_submission_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_submission_testcase_results
    ADD CONSTRAINT coding_submission_testcase_results_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.student_coding_submissions(id) ON DELETE CASCADE;


--
-- Name: coding_submission_testcase_results coding_submission_testcase_results_testcase_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coding_submission_testcase_results
    ADD CONSTRAINT coding_submission_testcase_results_testcase_id_fkey FOREIGN KEY (testcase_id) REFERENCES public.q_coding_testcases(id) ON DELETE SET NULL;


--
-- Name: contests contests_fk_teachers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contests
    ADD CONSTRAINT contests_fk_teachers FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: students fk_account_student; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fk_account_student FOREIGN KEY (id) REFERENCES public.accounts(id);


--
-- Name: teachers fk_account_teacher; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT fk_account_teacher FOREIGN KEY (id) REFERENCES public.accounts(id);


--
-- Name: contests_questions fk_contests_questions_contests; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contests_questions
    ADD CONSTRAINT fk_contests_questions_contests FOREIGN KEY (contest_id) REFERENCES public.contests(id) ON DELETE CASCADE;


--
-- Name: contests_questions fk_contests_questions_questions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contests_questions
    ADD CONSTRAINT fk_contests_questions_questions FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE;


--
-- Name: contests fk_contests_teacher; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contests
    ADD CONSTRAINT fk_contests_teacher FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: questions fk_parent_question; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fk_parent_question FOREIGN KEY (parent_id) REFERENCES public.questions(id);


--
-- Name: q_choice_details fk_question_images; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_choice_details
    ADD CONSTRAINT fk_question_images FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: q_images fk_question_images; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_images
    ADD CONSTRAINT fk_question_images FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: q_shortans_details fk_question_images; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_shortans_details
    ADD CONSTRAINT fk_question_images FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: q_truefalse_details fk_question_images; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_truefalse_details
    ADD CONSTRAINT fk_question_images FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: questions fk_questions_teacher; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fk_questions_teacher FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: student_option_submissions fk_student_option_submissions_contest_results; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_option_submissions
    ADD CONSTRAINT fk_student_option_submissions_contest_results FOREIGN KEY (contest_result_id) REFERENCES public.contest_results(id);


--
-- Name: student_option_submissions fk_student_option_submissions_questions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_option_submissions
    ADD CONSTRAINT fk_student_option_submissions_questions FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: students_classes fk_students_classes_classes; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students_classes
    ADD CONSTRAINT fk_students_classes_classes FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: students_classes fk_students_classes_students; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students_classes
    ADD CONSTRAINT fk_students_classes_students FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: contest_results fk_students_contests_contests; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_results
    ADD CONSTRAINT fk_students_contests_contests FOREIGN KEY (contest_id) REFERENCES public.contests(id);


--
-- Name: students_contests fk_students_contests_contests; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students_contests
    ADD CONSTRAINT fk_students_contests_contests FOREIGN KEY (contest_id) REFERENCES public.contests(id);


--
-- Name: contest_results fk_students_contests_students; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contest_results
    ADD CONSTRAINT fk_students_contests_students FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: students_contests fk_students_contests_students; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students_contests
    ADD CONSTRAINT fk_students_contests_students FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: classes fk_teacher_classes; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT fk_teacher_classes FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: q_coding_details q_coding_details_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_coding_details
    ADD CONSTRAINT q_coding_details_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE;


--
-- Name: q_coding_testcases q_coding_testcases_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_coding_testcases
    ADD CONSTRAINT q_coding_testcases_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE;


--
-- Name: student_coding_submissions student_coding_submissions_assignment_student_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_coding_submissions
    ADD CONSTRAINT student_coding_submissions_assignment_student_fkey FOREIGN KEY (assignment_student_id) REFERENCES public.coding_assignment_students(id) ON DELETE CASCADE;


--
-- Name: student_coding_submissions student_coding_submissions_contest_result_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_coding_submissions
    ADD CONSTRAINT student_coding_submissions_contest_result_id_fkey FOREIGN KEY (contest_result_id) REFERENCES public.contest_results(id) ON DELETE CASCADE;


--
-- Name: student_coding_submissions student_coding_submissions_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_coding_submissions
    ADD CONSTRAINT student_coding_submissions_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 5hxn45kwvZHgTWZLuDm4bpXM71T5YRqFNIyEOgeUTZO7WKovSIM1RzKQVw8hZcm

